### PR TITLE
Add sample `@use` to json docs.

### LINKED ISSUE #358: JSON not being exported
I'm sorry! I tried a lot, but I keep getting:

```
» [WARNING] Error reading file: ./build/sass-docs__exported.json
ENOENT: no such file or directory, open 'E:\_repositories\initial-css\build\sass-docs__exported.json'
```

The `abstracts/_index.scss` has:

```
@use '../../node_modules/sassdoc-theme-herman/scss/utilities';

/// Test
/// @colors brand-colors
/// @group colors
$colors: (
  'brand-colors': (
    'brand-orange': '#c75000',
    'brand-blue': '#0d7fa5',
  ),
  'status-colors': (
    'go': '#657e1b',
    'yield': '#c75000',
  ),
);

$herman: (
  'colors': $colors,
);

// Export to JSON
// @use '../../node_modules/sassdoc-theme-herman/scss/utilities' with (
//   $herman: $herman,
// );

// Export to JSON
@include utilities.export($herman);
```

The `.sassdocrc` file:

```
autofill:
  - "throw"
  - "content"
  - "require"
dest:
  - "./build"
exclude:
  - "./css/*"
  - "stylesheets/vendor/*"
groups:
  undefined: "General"
  components: "CSS components"
  configurations: "Configurations"
  font-stacks: "Font-stacks"
  qa: "Quality assurance"
  hacks: "Dirty Hacks & Fixes"
  helpers: "Helpers"
  normalizer: "Normalization"

  # testing
  # all items will be listed in the order given...
  api-config: Configuration
  api-json: Exporting Styles to JSON
  # testing
  # nested objects will create named subgroups...
  Public API:
    api-colors: Color Palettes
    api-fonts: Font Specimens
    api-scale: Ratios & Sizes
  Design Tokens:
    config-colors: _Colors
    config-fonts: _Fonts



package: "./package.json"
strict: true
theme: "herman"
verbose: true

display:
  access:
    - private
    - public
  alias: true
  watermark: true
  descriptionPath: "README.md"

herman:
  extraLinks:
  displayColors:
    - "hsl"
    - "hex"
  sass:
    jsonFile: "./build/sass-docs__exported.json"
    includePaths:
      - "./stylesheets/abstracts"
    use:
      - file: "constants"
        namespace: "*"
      - file: "font-stacks"
        namespace: "*"
      - file: "mixins"
        namespace: "*"
```

Can somebody help me, please?

### PR DESCRIPTION
**Pull request by jgerigmeyer**
Closes #366.

Fixes #358 & #359.

### CODE REVIEW

**Review by mirisuzanne — COMMENTED** [review]
Looks pretty good. I suppose the other option would be removing utilities from the auto-used modules, so that we actually have to use it in the demos.

Right now it seems a bit inconsistent where we are adding it or not? See eg https://deploy-preview-373--herman-staging.netlify.app/api_json-export.html#mixin--export and a few others that reference the utility namespace without explicitly using it.

**Comment by jgerigmeyer** [comment]
> Looks pretty good. I suppose the other option would be removing utilities from the auto-used modules, so that we actually have to use it in the demos.

@mirisuzanne I'm open to that, but it would mean our sample code would have e.g. `@use 'utilities';`, where most users would need something like `@use '~/sassdoc-theme-herman/scss/utilities';` -- is that still preferred?

> Right now it seems a bit inconsistent where we are adding it or not? See eg https://deploy-preview-373--herman-staging.netlify.app/api_json-export.html#mixin--export and a few others that reference the utility namespace without explicitly using it.

Sure, I can address that.

**Comment by mirisuzanne** [comment]
> I'm open to that, but it would mean our sample code would have e.g. `@use 'utilities';`, where most users would need something like `@use '~/sassdoc-theme-herman/scss/utilities';` -- is that still preferred?

That makes sense. I'm not sure? Happy to go either way.

**Comment by jgerigmeyer** [comment]
> Looks pretty good. I suppose the other option would be removing utilities from the auto-used modules, so that we actually have to use it in the demos.
> 
> Right now it seems a bit inconsistent where we are adding it or not? See eg https://deploy-preview-373--herman-staging.netlify.app/api_json-export.html#mixin--export and a few others that reference the utility namespace without explicitly using it.

@mirisuzanne Both addressed in https://github.com/oddbird/sassdoc-theme-herman/pull/373/commits/536d4330fa3f89f81cec06701759c053fa6a8aa2 -- what do you think?

**Review by mirisuzanne — APPROVED** [review]
looks great!

**Pull request merged**
